name: feedback_loop
description: "Une plateforme de retours et de votes d'idées"
publish_to: 'none'
version: 0.0.1


environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_riverpod: ^3.4.3
  go_router: ^18.0.1
  shared_preferences: ^2.5.5
  flutter_native_splash: ^2.4.8
  readmore: ^3.0.0
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/icon/
    - assets/image/
    - assets/image/logo/


# Configuration de l'icone de l'application
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/feedback-loop.jpg
  adaptative_icon_background: "#FFFFFF"

  web:
    generate: true
    image_path: assets/icon/feedback-loop.jpg
    background_color: "#FFFFFF"


# Configuration du splash screen
flutter_native_splash:
  # config globales
  android: true 
  ios: true
  web: true

  # splash du thème clair
  color: "#FFFFFF"
  image: assets/splash_screen/splash-screen-light.png

  # splash du thème sombre
  color_dark: "#121214"
  image_dark: assets/splash_screen/splash-screen-dark.png